# Data Structures

## Candidate (object)

+ id: 1 (number, required)
+ name: Candidate #1 (required)
+ description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus sequi asperiores voluptate, inventore culpa dolores nostrum consequuntur autem. Perspiciatis dolor, nisi alias dolore autem! A sequi consequuntur eveniet sapiente accusamus."